name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ppj.jurnalsinta.id
          username: jurz2196
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: 22
          script: |
            cd /home/jurz2196/repo/simonju
            git pull origin master
